apiVersion: v1
kind: Service
metadata:
  name: kubernetes-auth-server
spec:
  ports:
  - port: 80
    targetPort: app-port
    protocol: TCP
  selector:
    app: kubernetes-auth-server
  type: LoadBalancer
